FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN mkdir -p /app/data && chmod 777 /app/data
RUN pip install --no-cache-dir -r requirements.txt
COPY src/ /app/src
CMD ["uvicorn", "src.store.main:app", "--host", "0.0.0.0", "--port", "8000"]
