FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src/ /app/src
CMD ["uvicorn", "src.demo_service_1.main:app", "--host", "0.0.0.0", "--port", "8000"]
